import org.jooq.util.jaxb.Configuration;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rgra' at '05.02.17 12:50' with Gradle 2.14.1
 *
 * @author rgra, @date 05.02.17 12:50
 */
public class JooqSchemaGen {
	public static void main(String[] args) throws Exception {

		Configuration config = org.jooq.util.GenerationTool.load(JooqSchemaGen.class.getResourceAsStream("test.xml"));
		org.jooq.util.GenerationTool.main(config);
	}
}
